### ISSUE TITLE
more example

### ISSUE THREAD

**Issue by semutnest** [felangel/sealed_flutter_bloc#1]
Hello @felangel ,

Still guessing. Could you please provide us more samples, things related to changes in state data such as the use of copyWith ?

Thank's.

**Comment by felangel** [comment]
Hi @semutnest 👋 
Thanks for opening an issue!

Yeah I will definitely add some more examples over the next week 👍

**Comment by semutnest** [comment]
Ok @felangel , I can't wait.

Thank's.

**Comment by felangel** [comment]
@semutnest added an [infinite list example](https://github.com/felangel/sealed_flutter_bloc/tree/master/examples/flutter_infinite_list). More to come soon 👍

**Comment by mancem72** [comment]
@felangel TODOS example please....

**Comment by felangel** [comment]
@mancem72 I’ll do Todos next haha 😄

**Comment by aytunch** [comment]
@felangel Hi, this must be important package since authored by you. But I don't understand what it is for because there is no readme or tutorial. Can we have a description please?

**Comment by felangel** [comment]
@aytunch haha sorry about that! I'll improve the documentation later today 👍
