### ISSUE TITLE
Please update to flutter_bloc ^6.0.1

### ISSUE THREAD

**Issue by waqasakram117** [felangel/sealed_flutter_bloc#9]
**sealed_flutter_bloc ^4.0.0 which depends on flutter_bloc ^4.0.0 and my project depends on flutter_bloc ^6.0.1, version solving failed**

**Please upgrade with**
flutter_bloc ^6.0.1

**Comment by felangel** [comment]
Hi @waqasakram117 👋
Thanks for opening an issue!

I’ll have it updated shortly 👍

**Comment by felangel** [comment]
v6.0.0 is out 🎉
